#!/bin/sh
# Copyright (c) 2011 to 2017 Erik Boasson
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License. */

if [ $# -ne 1 ] ; then
    echo "usage: $0 PROGRAM  --  (and then copy-&-paste a line from lkst)" >&2
    exit 1
fi

p=$1
f=/tmp/gdbstackdump-commands.$$

read
x=`echo $REPLY | sed -e 's/^.* pid \([0-9][0-9]*\) st/\1/'`
echo '$x'
set -- $x
pid=$1
shift
while [ $# -ge 1 ] ; do
    echo "l *$1" >>$f
    shift
done
gdb -batch -x $f $p $pid
rm -f $f
